SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../src/collision.v $(PWD)/../../src/coll_table.v
TOPLEVEL = collision
MODULE = collision_test
include $(shell cocotb-config --makefiles)/Makefile.sim
