name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create commit_id.json
        shell: bash
        run: |
          jq -n \
            --arg app "Customised TT08 OL2 2.1.1" \
            --arg repo "${{ github.server_url }}/${{ github.repository }}" \
            --arg commit "${{ github.sha }}" \
            --arg workflow_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            '{app: $app, repo: $repo, commit: $commit, workflow_url: $workflow_url}' \
            > tt_submission/commit_id.json

      - name: Publish tt_submission artifact
        uses: actions/upload-artifact@v4
        with:
          name: tt_submission
          path: |
            src/*
            docs/*
            tt_submission/*
            info.yaml
            LICENSE

      - name: Upload gds_render (png) artifact
        uses: actions/upload-artifact@v4
        with:
          name: gds_render
          path: 'gds_render.png'

  precheck:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@tt08

  gl_test:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: MichaelBell/tt-gds-action/gl_test@tt08

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt08
