FILE = tt_um_cejmu
#TARGET=synth_ice40
MODULES = baverage/baverage.sv cla/cla.sv cla/cla_full_adder.sv io_serdes/io_serdes.sv rca/rca.sv rca/rca_fulladder.sv coin_acceptor/coin_acceptor.sv

include Makefile.inc
