# Top and HDMI stuff
VERILOG += ./top.v \
	./ecp5pll.sv \
	./hdmi.v

# TT design
VERILOG += \
	../src/hvsync_gen.v \
	../src/scale_rom.v \
	../src/tria.v \
	../src/tt_um_top.v \
	../src/voice.v \


DEVICE=85k

include ulx3s.mk

